### PR TITLE
Adding Alex Bank endpoint

### PR DESCRIPTION
**Pull request by carl-dot-dot**

### CODE REVIEW

**Review by vadkor — CHANGES_REQUESTED** [review]
The entry is not in the alphabetical order, comma in the previous line missing.
If you haven't done that yet, please email us on contact@consumerdatastandards.gov.au to verify your relationship with Alex Bank.

**Comment by carl-dot-dot** [comment]
> The entry is not in the alphabetical order, comma in the previous line missing. If you haven't done that yet, please email us on [contact@consumerdatastandards.gov.au](mailto:contact@consumerdatastandards.gov.au) to verify your relationship with Alex Bank.

**Comment by carl-dot-dot** [comment]
Updated and email send.
Thanks

**Review by vadkor — CHANGES_REQUESTED** [review]
The first four entries are "The Big Four". They have their own order. Alex Bank should go between Adelaide Bank and AMP Bank.

**Review by vadkor — APPROVED** [review]

**Pull request merged**
