### PR TITLE
Update datasources.json

### PR DESCRIPTION
**Pull request by piliaris**
Modifying Suncorp URL due to change of product service endpoint.

### CODE REVIEW

**Comment by tom-schier** [comment]
Validated public endpoints against our Postman collection test runs. All OK.

@piliaris We would need some proof your association with the financial institution on who's behalf your are acting on. This should  via an independent channel, for instance email. Thanks

**Comment by piliaris** [comment]
Hi @tom-schier - did you receive the email I sent from my Suncorp account?

**Comment by michaelpiliaris** [comment]
Hi @tom-schier - I've created a github account under my suncorp email address to confirm my representation from Suncorp.  Hope this helps.  Thanks

**Comment by tom-schier** [comment]
@michaelpiliaris Could you please send an email to contact@consumerdatastandards.gov.au . Thanks

**Comment by michaelpiliaris** [comment]
Email has been sent to contact@consumerdatastandards.gov.au just now.

**Pull request merged**
