### PR TITLE
Update datasources.json

### PR DESCRIPTION
**Pull request by AuswideBank**
Added Auswide Bank to the data sources

### CODE REVIEW

**Comment by vadkor** [comment]
@AuswideBank, the _icon_ is fine, but the _url_ doesn't look right. I'm getting 404. Have you tried adding these details in the Banks section of the Comparator manually? Also, the CORS seems to be blocked even when the _url_ is https://api.auswidebank.com.au/OpenBanking/cds-au/v1 (OPTIONS is not allowed, but it should be).

Please don't forget to email us at cdr-data61@csiro.au to verify the association of your GitHub persona with the bank.

**Review by vadkor — CHANGES_REQUESTED** [review]
Also, your fork is out of date. Please merge in new changes and resolve the conflict.

**Review by vadkor — CHANGES_REQUESTED** [review]
We haven't heard back from you. Please respond.

Your fork is out of date now. Please merge in new changes and resolve the conflict.

**Review by vadkor — APPROVED** [review]
@AuswideBank, we fixed the URL (by removing the suffix) for you and resolved the merged conflict.

We are waiting for your email to us at cdr-data61@csiro.au to verify the association of your GitHub persona with the bank. Once we receive it your PR will be merged.

**Comment by AuswideBank** [comment]
Hi @vadkor, Thanks for your assistance.  Have emailed you at cdr-data61@csiro.au.  We believe that we have fixed the options issue now.

**Pull request merged**
