### PR TITLE
Add Police Bank

### PR DESCRIPTION
**Pull request by speedyps**
I am working for SISS Data Services who is hosting the Police Bank Product API.

The Police Bank API endpoint has been added to the datasources.json.

### CODE REVIEW

**Review by vadkor — APPROVED** [review]

**Comment by deepsol-oba** [comment]
@speedyps - Peter, is there a chance that the handling of the combination of x-min-v and x-v needs review? When using x-min-v = 1 and x-v = 999, the x-v response header has 999.

I believe - might be wrong - that the expectation is that the highest supported version should be returned. (x-v = 3)
https://consumerdatastandardsaustralia.github.io/standards/#http-headers
"The holder should respond with the highest supported version between x-min-v and x-v"

**Comment by speedyps** [comment]
> @speedyps - Peter, is there a chance that the handling of the combination of x-min-v and x-v needs review? When using x-min-v = 1 and x-v = 999, the response status is 406.
> 
> I believe - might be wrong - that the expectation is that the highest supported version should be returned. (x-v = 3)
> https://consumerdatastandardsaustralia.github.io/standards/#http-headers
> "The holder should respond with the highest supported version between x-min-v and x-v"

Hey @deepsol-oba.

This has been corrected on the API.

Cheers

**Comment by speedyps** [comment]
Also @deepsol-oba, I notice NAB returns 999 for x-v in the scenario mentioned - which I think you had in the original comment.

**Comment by deepsol-oba** [comment]
@speedyps - Peter - very cool ... for x-min-v = 1 and x-v = 999, we are now seeing in response status code 200 and x-v =3 (in header).
Looking good !!!

**Comment by deepsol-oba** [comment]
> Also @deepsol-oba, I notice NAB returns 999 for x-v in the scenario mentioned - which I think you had in the original comment.

@speedyps - yes, apologies ... we are working on a version testing tool based on the comparator datasource.json and was sending some notes where we noticed a potential issue which might prevent a x-v detection for the purpose of comparison. My copy-and-paste gremlin got the better of me.

**Comment by deepsol-oba** [comment]
@speedyps - Hi Peter, something else I noticed today. I understand that DateTimeString fields need to follow RFC-3339. Looking at your payload I wasn't able to see either Z or the offset. Not sure if this intended and thought I share the observation.

**Comment by speedyps** [comment]
@deepsol-oba, thanks for that, working on it now.  Should be resolved early next week - am going with the offset.

**Pull request merged**
