### PR TITLE
P&N Bank PRD uri

### PR DESCRIPTION
**Pull request by VladPNBank**
Hello, could you please merge P&N Bank PRD uri. Thank you

### CODE REVIEW

**Review by vadkor — APPROVED** [review]
@VladPNBank please send us a message at cdr-data61@csiro.au to verify your association and representation of P&N Bank. Once we receive your email your PR will be merged.

**Comment by deepsol-oba** [comment]
@VladPNBank - is there a chance that the handling of the combination of x-min-v and x-v needs review? When using x-min-v = 1 and x-v = 999, the x-v response header has 999.

I believe - might be wrong - that the expectation is that the highest supported version should be returned. (x-v = 3 ?)
https://consumerdatastandardsaustralia.github.io/standards/#http-headers
"The holder should respond with the highest supported version between x-min-v and x-v"

**Comment by VladPNBank** [comment]
@deepsol-oba , I've raised a ticket to fix it. I'll update you once I have resolution. Thank you.

**Comment by VladPNBank** [comment]
> @VladPNBank - is there a chance that the handling of the combination of x-min-v and x-v needs review? When using x-min-v = 1 and x-v = 999, the response status is 406.
> 
> I believe - might be wrong - that the expectation is that the highest supported version should be returned. (x-v = 3 ?)
> https://consumerdatastandardsaustralia.github.io/standards/#http-headers
> "The holder should respond with the highest supported version between x-min-v and x-v"

This is fixed

**Pull request merged**
