### PR TITLE
add ING base url

### PR DESCRIPTION
**Pull request by dorbat01**

### CODE REVIEW

**Comment by perlboy** [comment]
This endpoint contains invalid payloads primarily with respect to incorrectly populated `additionalValue`:
image

We have detected 26 errors, 27 warnings within 453 tests:
image

**Comment by CDR-API-Stream** [comment]
@dorbat01, happy to merge this but your persona gives no indication if you are associated with ING.  If you could confirm via email to cdr-data61@csiro.au that would be appreciated.

**Comment by CDR-API-Stream** [comment]
@perlboy, the errors you have identified are not actual errors according to the standards.  The rules for additionalValue indicate when they should be included and what type they should be in that case.  It does not mean the field must be null if the relevant type does not require them.

Also, we do not require that an API is compliant for them to be included in the comparator.  Compliance is an ACCC concern.

**Comment by perlboy** [comment]
@CDR-API-Stream the content included in this `additionalValue` field cannot be assumed to be read by any recipient software and this particular endpoint is supplying an application frequency within this field:
image

On this basis we will continue to treat it as an error.

**Comment by perlboy** [comment]
Further on this `additionalValue` is missing when mandatory for `/banking/products/2aeb8d10-5633-4c68-A1e5-0cd1e4ed7b1a`
image

image

**Comment by JamesMBligh** [comment]
I have confirmed the connection with ING out of band

**Comment by dorbat01** [comment]
@perlboy, we have updated the data in production accordingly.  Please verify.

**Comment by perlboy** [comment]
Hi @dorbat01,

An extract of the last run is below, apologies for the formatting, we have a nicer gui presentation of this. If you want to clarify some things feel free to jump on the DataRight.io Slack.

| path | message | severity | fields |
|-|-|-|-|
| /banking/products/98290a00-39c5-4157-82ce-e725e305237b | Additional Value should be null when Deposit Rate Type is VARIABLE | ERROR | data.depositRates[1].additionalValue |
| /banking/products/98290a00-39c5-4157-82ce-e725e305237b | Additional Value should be null when Deposit Rate Type is VARIABLE | ERROR | data.depositRates[1].depositRateType |
| /banking/products/98290a00-39c5-4157-82ce-e725e305237b | Additional Value should be null when Deposit Rate Type is VARIABLE | ERROR | data.depositRates[2].additionalValue |
| /banking/products/98290a00-39c5-4157-82ce-e725e305237b | Additional Value should be null when Deposit Rate Type is VARIABLE | ERROR | data.depositRates[2].depositRateType |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[2].tiers |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[5].tiers |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[3].tiers |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[4].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[2].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[3].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[6].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[1].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[4].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[5].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[7].tiers |
| /banking/products/26ab99ae-81ed-44d0-933f-b6d9f0f4b004 | Contains an empty array | WARNING | data.depositRates[0].tiers |
| /banking/products/b7bb9da4-3913-484c-8d2d-3fc99b9b4a72 | Contains an empty array | WARNING | data.depositRates[0].tiers |
| /banking/products/b7bb9da4-3913-484c-8d2d-3fc99b9b4a72 | Contains an empty array | WARNING | data.depositRates[1].tiers |
| /banking/products/2aeb8d10-5633-4c68-a1e5-0cd1e4ed7b1a | Contains an empty array | WARNING | data.depositRates[0].tiers |
| /banking/products/2aeb8d10-5633-4c68-a1e5-0cd1e4ed7b1a | Contains an empty array | WARNING | data.depositRates[1].tiers |
| /banking/products/5dfd508b-e0c5-435c-a332-49d138cfdbaf | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].additionalValue |
| /banking/products/5dfd508b-e0c5-435c-a332-49d138cfdbaf | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].featureType |
| /banking/products/2a1b3e3f-b724-449b-a400-6bda399de68d | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].additionalValue |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[6].tiers |
| /banking/products/2a1b3e3f-b724-449b-a400-6bda399de68d | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].featureType |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[0].tiers |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[7].tiers |
| /banking/products/544ca08a-57ec-45a3-85ef-0a398646795a | Contains an empty array | WARNING | data.depositRates[1].tiers |
| /banking/products/5031dc6b-6993-4de1-8e0b-a96de30c2f28 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[8].additionalValue |
| /banking/products/5031dc6b-6993-4de1-8e0b-a96de30c2f28 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[8].featureType |
| /banking/products/a4ea7460-9e69-499d-84dd-f281c7a04130 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[10].additionalValue |
| /banking/products/a4ea7460-9e69-499d-84dd-f281c7a04130 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[10].featureType |
| /banking/products/a4ea7460-9e69-499d-84dd-f281c7a04130 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].additionalValue |
| /banking/products/a4ea7460-9e69-499d-84dd-f281c7a04130 | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[9].featureType |
| /banking/products/ef0c2da9-0f12-40e9-ad5d-4fce22f5fd9a | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[0].additionalValue |
| /banking/products/ef0c2da9-0f12-40e9-ad5d-4fce22f5fd9a | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[0].featureType |
| /banking/products/ef0c2da9-0f12-40e9-ad5d-4fce22f5fd9a | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[1].additionalValue |
| /banking/products/ef0c2da9-0f12-40e9-ad5d-4fce22f5fd9a | Additional Value should be null with Feature Type is one of UNLIMITED_TXNS, OFFSET, OVERDRAFT, REDRAW, BALANCE_TRANSFERS, DIGITAL_BANKING, NPP_PAYID, NPP_ENABLED, DONATE_INTEREST, OTHER | WARNING | data.features[1].featureType |

**Comment by deepsol-oba** [comment]
@perlboy Hi Stuart - wondering (I am not associated with ING) - Why is an empty array a problem. Have been curious about this before and haven't been able to find a direction on this in the CDS.

**Comment by nils-work** [comment]
Hi @deepsol-oba, it looks like the report describes it as a WARNING that something may be missing, but the [array is optional](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingproductdepositrate).
Some of the products mentioned, including `544ca08a-57ec-45a3-85ef-0a398646795a` don't have the array at all, which could be valid.

**Comment by perlboy** [comment]
@nils-work @deepsol-oba Yes, the intent of that warning is to indicate "This value is [], are you sure?". Admittedly, it appears even `null` is throwing this warning so I've opened a bug report for us internally and edited these out for now.

With that said @dorbat01, assuming my quick checks to provide the above response are accurate, your API does not appear to be handling versioning correctly as the `x-v`==3 should result in a downgraded V2 payload (as you don't support V3):
```
stuart@stuart-desktop:~$ curl --location --request GET 'https://apic.ing.com.au/cds-au/v1/banking/products/544ca08a-57ec-45a3-85ef-0a398646795a' --header 'x-v: 3' --header 'x-min-v: 1' -w "\n"
{ "errors": [
                {
                  "code": "0004",
                  "title": "Not Acceptable",
                  "detail": "Missing or invalid x-v header."
                }
              ]
            }

```

**Comment by dorbat01** [comment]
> @nils-work @deepsol-oba Yes, the intent of that warning is to indicate "This value is [], are you sure?". Admittedly, it appears even `null` is throwing this warning so I've opened a bug report for us internally and edited these out for now.
> 
> With that said @dorbat01, assuming my quick checks to provide the above response are accurate, your API does not appear to be handling versioning correctly as the `x-v`==3 should result in a downgraded V2 payload (as you don't support V3):
> 
> ```
> stuart@stuart-desktop:~$ curl --location --request GET 'https://apic.ing.com.au/cds-au/v1/banking/products/544ca08a-57ec-45a3-85ef-0a398646795a' --header 'x-v: 3' --header 'x-min-v: 1' -w "\n"
> { "errors": [
>                 {
>                   "code": "0004",
>                   "title": "Not Acceptable",
>                   "detail": "Missing or invalid x-v header."
>                 }
>               ]
>             }
> ```

@perlboy, yeah, I am well aware of this one.  The fix is scheduled to release in Nov.

**Pull request merged**
